name: Build OmniBox JSON

on:
  schedule:
    - cron: '0 */6 * * *'   # 每6小时自动运行一次
  workflow_dispatch:       # 允许手动运行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run convert script
        run: node convert.mjs

      - name: Commit generated file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add omnibox.json
          git commit -m "auto update" || echo "No changes"
          git push
